repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [
          '--autofix',
          '--indent', '4',
          '--no-sort-keys',
        ]
      #    -   id: requirements-txt-fixer
      - id: trailing-whitespace
  #-   repo: meta
  #    hooks:
  #    -   id: check-hooks-apply
  #    -   id: check-useless-excludes
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.5.3
    hooks:
      - id: pylint
        additional_dependencies: [pylint-venv]
        args: ['--disable=all']
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [-lll, --recursive]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v0.13.0
    hooks:
      - id: detect-secrets
        exclude: "Pipfile.lock"
        args: ['--baseline', '.secrets.baseline']
