#!/bin/bash

set -ex

if [[ ! "$BRANCH_NAME" = "main" && ! "$BRANCH_NAME" = "prod" ]]; then
	echo "$BRANCH_NAME is not a deployable branch. Stopping."
	exit 0
fi

ENV=stage
DOMAIN=api.allizom.org
if [[ "$BRANCH_NAME" = "prod" ]]; then
	ENV=$BRANCH_NAME
	DOMAIN=api.mozilla.org
fi

for e in mozilla-api-${ENV}; do
  cp k8s/deploy.yaml k8s/deploy-${e}.yaml
  sed -i -e "s|@SHORT_SHA@|$SHORT_SHA|g" -e "s|@PROJECT@|$e|g" k8s/deploy-${e}.yaml
  gcloud config set project "$e"
  stuff=($(gcloud container clusters list | grep "$e" | awk '{print $1,$2}'))
  cluster=${stuff[0]}
  zone=${stuff[1]}
  gcloud container clusters get-credentials $cluster --zone=$zone
  kubectl apply -f k8s/ns.yaml
  kubectl apply -f k8s/deploy-${e}.yaml
  kubectl apply -f k8s/svc.yaml
  kubectl apply -f k8s/ing.yaml
  kubectl apply -f k8s/cert.yaml
  IP=`kubectl get ingress --namespace containerized-microservice-template containerized-microservice-template-ing -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`
  gcloud --project=mozilla-api-${ENV} dns record-sets transaction start --zone="mozilla-api-${ENV}-zone"
  gcloud --project=mozilla-api-${ENV} dns record-sets transaction add 35.244.248.226 --name="jbi.${DOMAIN}" --ttl="30" --type="A" --zone="mozilla-api-${ENV}-zone"
  gcloud --project=mozilla-api-${ENV} dns record-sets transaction execute --zone="mozilla-api-${ENV}-zone"
  kubectl -ncontainerized-microservice-template set env deployments/containerized-microservice-template DEPLOYED_ON=$(date +%s)
done