#!/bin/bash

set -ex

if [[ ! "$BRANCH_NAME" = "main" && ! "$BRANCH_NAME" = "prod" ]]; then
	echo "$BRANCH_NAME is not a deployable branch. Stopping."
	exit 0
fi

ENV=stage

DOMAIN=api.data.allizom.org
if [[ "$BRANCH_NAME" = "prod" ]]; then
	ENV=$BRANCH_NAME
	DOMAIN=api.data.mozilla.org
fi

SUBDOMAIN=example
SVC_NAME=containerized-microservice-template

FULL_DOMAIN=${SUBDOMAIN}.${DOMAIN}
PROJ_ENV=mozilla-api-${ENV}
ENV_ZONE=mozilla-api-${ENV}-zone

for e in ${PROJ_ENV}; do
    cp k8s/deploy.yaml k8s/deploy-${e}.yaml
    sed -i -e "s|@SHORT_SHA@|$SHORT_SHA|g" -e "s|@PROJECT@|$e|g" k8s/deploy-${e}.yaml
    cp k8s/deploy.yaml k8s/cert-${e}.yaml
    sed -i -e "s|@SVC_NAME@|$SVC_NAME|g" -e "s|@FULL_DOMAIN@|$FULL_DOMAIN|g" k8s/cert-${e}.yaml
    cp k8s/deploy.yaml k8s/ing-${e}.yaml
    sed -i -e "s|@SVC_NAME@|$SVC_NAME|g" -e "s|@FULL_DOMAIN@|$FULL_DOMAIN|g" k8s/ing-${e}.yaml

    gcloud config set project "$e"
    stuff=($(gcloud container clusters list | grep "$e" | awk '{print $1,$2}'))
    cluster=${stuff[0]}
    zone=${stuff[1]}
    gcloud container clusters get-credentials $cluster --zone=$zone
    kubectl apply -f k8s/ns.yaml
    kubectl apply -f k8s/deploy-${e}.yaml
    kubectl apply -f k8s/svc.yaml
    kubectl apply -f k8s/ing-${e}.yaml
    kubectl apply -f k8s/cert-${e}.yaml
    NEW_IP=`kubectl get ingress --namespace ${SVC_NAME} ${SVC_NAME}-ing -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`
    OLD_IP=`gcloud --project=${PROJ_ENV} dns record-sets list --zone="${ENV_ZONE}" | grep ^${FULL_DOMAIN} | sed "s/^.* //"`
    if [ "$OLD_IP" == "$NEW_IP" ]; then
      echo "No ingress IP change. No DNS action needed."
    else
      if [ "$OLD_IP" == "" ]; then
          echo "No existing DNS record! Adding a new one."
      elif [ "$OLD_IP" != "$NEW_IP" ]; then
          echo "Ingress ip has changed! Deleting and readding."
          gcloud --project=${PROJ_ENV} dns record-sets transaction start --zone="${ENV_ZONE}"
          gcloud --project=${PROJ_ENV} dns record-sets transaction remove $OLD_IP --name="${FULL_DOMAIN}" --ttl="30" --type="A" --zone="${ENV_ZONE}"
          gcloud --project=${PROJ_ENV} dns record-sets transaction execute --zone="${ENV_ZONE}"
      fi
      gcloud --project=${PROJ_ENV} dns record-sets transaction start --zone="${ENV_ZONE}"
      gcloud --project=${PROJ_ENV} dns record-sets transaction add $NEW_IP --name="${FULL_DOMAIN}" --ttl="30" --type="A" --zone="${ENV_ZONE}"
      gcloud --project=${PROJ_ENV} dns record-sets transaction execute --zone="${ENV_ZONE}"
    fi
    kubectl -n${SVC_NAME} set env deployments/${SVC_NAME} DEPLOYED_ON=$(date +%s)
done
