apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: containerized-microservice-template
  name: containerized-microservice-template
  namespace: containerized-microservice-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerized-microservice-template
  template:
    metadata:
      labels:
        app: containerized-microservice-template
    spec:
      containers:
      - image: gcr.io/@PROJECT_NAME@/github.com/mozilla-it/@REPO_NAME@:@SHORT_SHA@
        imagePullPolicy: Always
        name: containerized-microservice-template
        env:
          - name: PROJECT
            value: "@PROJECT@"
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10